config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new", as: "new"
  get "tasks/:id", to: "tasks#show", as: "task"
  post "tasks", to: "tasks#create", as: "create"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update", as: :edit_post
  delete "tasks/:id", to: "tasks#destroy", as: :destroy
  # resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.delete
    redirect_to tasks_path(@task)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.number_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Index page</h1>
<br>
<h2>Here are all the tasks :</h2>

<ul>
  <% @tasks.each do |task| %>
    <li>Task : <%= link_to task.title, task %></li>
  <% end %>
</ul>

<p><%= link_to "Add a new task", new_url %></p>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task</h1>
<br>
<p><strong>Task : </strong><%= @task.title %></p>
<p><strong>Details : </strong><%= @task.details %></p>
<p><strong>Done ? </strong><%= @task.completed %></p>
<br>
<p><%= link_to "Edit this task", edit_task_url %></p>
<%= link_to "Delete '#{@task.title}'",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
<br>
<br>
<p><%= link_to "Return to see all tasks", tasks_url %></p>
<br>